-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.17-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.1.0.6116
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for gamedaydb
CREATE DATABASE IF NOT EXISTS `gamedaydb` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `gamedaydb`;

-- Dumping structure for table gamedaydb.games
CREATE TABLE IF NOT EXISTS `games` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `thumbnailImage` varchar(200) NOT NULL,
  `bannerImage` varchar(200) NOT NULL,
  `title` varchar(100) NOT NULL,
  `releaseDate` varchar(200) NOT NULL,
  `platforms` varchar(200) NOT NULL,
  `developers` varchar(200) NOT NULL,
  `genres` varchar(200) NOT NULL,
  `description` varchar(5000) NOT NULL DEFAULT '',
  `win` int(1) NOT NULL DEFAULT 0,
  `xbox` int(1) NOT NULL DEFAULT 0,
  `ps` int(1) NOT NULL DEFAULT 0,
  `switch` int(1) NOT NULL DEFAULT 0,
  `trailer` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table gamedaydb.games: ~3 rows (approximately)
/*!40000 ALTER TABLE `games` DISABLE KEYS */;
INSERT INTO `games` (`id`, `thumbnailImage`, `bannerImage`, `title`, `releaseDate`, `platforms`, `developers`, `genres`, `description`, `win`, `xbox`, `ps`, `switch`, `trailer`) VALUES
	(1, '/img/LittleNightmaresThumb.png', '/img/LittleNightmaresBanner.jpg', 'Little Nightmare', 'Initial release date: December 9, 2020', 'PlayStation 4, Xbox One, PlayStation 5, Nintendo Switch, Xbox Series X and Series S, Microsoft Windows, Google Stadia', 'Tarsier Studios, Supermassive Games', 'Puzzle Video Game, Platform game, Survival horror', 'Little Nightmares II is similar to its predecessor; it takes place in a 2.5D world. The player must explore the world, occasionally encountering platformer-like situations or being blocked by puzzles that must be solved to proceed. Unlike the first game, the player is not completely helpless; Mono has the ability to grab certain items and swing them to break objects or to fight back against smaller foes, although he, like Six, must rely on stealth and the environment to evade larger foes. The player is also given the ability to call out to Six and hold her hand to make sure they stay together and must often work together with her to solve environmental puzzles and defeat or evade enemies. The game also features collectible hats and glitching remains, the latter of which will unlock an additional scene upon collecting them all.', 0, 1, 1, 1, 'https://www.youtube.com/watch?v=AI9zBBTyX-E'),
	(2, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(3, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(4, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(5, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(6, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(7, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(8, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(9, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(10, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(11, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(12, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(13, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(14, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(15, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(16, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(17, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(18, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(19, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(20, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4'),
	(21, '/img/ValhallaThumb.png', '/img/ValhallaBanner.jpg', 'Assassin\'s Creed Valhalla', 'Initial release date: November 10, 2020', 'Xbox Series X and Series S, PlayStation 4, PlayStation 5, Xbox One, Amazon Luna, Google Stadia, Microsoft Windows', 'Ubisoft Milan, Ubisoft Montreal', 'Stealth game, Action-adventure game, Nonlinear gameplay', 'Assassin\'s Creed Valhalla is a 2020 action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It is the twelfth major installment in the Assassin\'s Creed series, and the successor to 2018\'s Assassin\'s Creed Odyssey. Principally set in the years 872–878 AD, the game recounts a fictional story during the Viking expansions into the British Isles. Players control Eivor Varinsdottir, a Viking raider who becomes embroiled in the centuries-old conflict between the Assassin Brotherhood, who fight for peace and liberty, and the Templar Order, who desire peace through control.The modern-day portion of the story is set in the 21st century and follows Layla Hassan, an Assassin who relives Eivor\'s memories so as to find a way to save the Earth from destruction. ', 1, 1, 1, 1, 'https://www.youtube.com/watch?v=ssrNcwxALS4');
/*!40000 ALTER TABLE `games` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
